name: ✨ Feature Request
description: Suggest a new idea or gameplay mechanic
title: '[Feature] <your idea>'
labels: [enhancement, needs review]
body:
  - type: markdown
    attributes:
      value: |
        Got a cool idea? Let's hear it!

  - type: input
    id: idea-summary
    attributes:
      label: One-liner summary
      placeholder: e.g. Add ritual that clears mobs
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Describe the feature
      description: What would this add to the mod? How does it fit the Aztec / ritual theme?
      placeholder: Explain your idea here...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Hints (optional)
      description: If you know how it could be implemented, explain here
    validations:
      required: false

  - type: checkboxes
    id: consent
    attributes:
      label: Contribution
      description: How do you want to contribute?
      options:
        - label: I just had the idea, I can't code it.
        - label: I’d like to help implement it!
